// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUeRBC-UNlYSu5bswrDuQGJKlW2rifAA8',
    appId: '1:143496518364:web:ca942a409f528739d0b219',
    messagingSenderId: '143496518364',
    projectId: 'pipe-detection',
    authDomain: 'pipe-detection.firebaseapp.com',
    storageBucket: 'pipe-detection.appspot.com',
    measurementId: 'G-B535GTMFRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiDq5Per44fNfomOjWcaaxMf0MgnuU5so',
    appId: '1:143496518364:android:6ddc4fe401ca799fd0b219',
    messagingSenderId: '143496518364',
    projectId: 'pipe-detection',
    storageBucket: 'pipe-detection.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTCXlp65-U4pTPv7UYVEkGBagbBOAp4EU',
    appId: '1:143496518364:ios:914bd7a6c4485203d0b219',
    messagingSenderId: '143496518364',
    projectId: 'pipe-detection',
    storageBucket: 'pipe-detection.appspot.com',
    iosClientId: '143496518364-pqgp3gthpa7v6bo488ovkkvj1flukmjk.apps.googleusercontent.com',
    iosBundleId: 'com.example.pipeDetectionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTCXlp65-U4pTPv7UYVEkGBagbBOAp4EU',
    appId: '1:143496518364:ios:89d26d9f9178ef8cd0b219',
    messagingSenderId: '143496518364',
    projectId: 'pipe-detection',
    storageBucket: 'pipe-detection.appspot.com',
    iosClientId: '143496518364-jed47vk4m1a8dnu4pg888fs7fbujn6kp.apps.googleusercontent.com',
    iosBundleId: 'com.example.pipeDetectionApp.RunnerTests',
  );
}
